//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace NSTest {
    
    public partial class MainWindow : Window {
        MainWindowViewModel _vm;
        public MainWindow() {
            this.DataContext = (_vm = new MainWindowViewModel());
            InitializeComponent();
        }
    }
}
